- name: Set up environment
  hosts: all
  roles:
    - role: alacritty
    - role: i3
    - role: i3blocks
    - role: i3status
    - role: rofi
    - role: rofi_calc
    - role: streamdeck
    - role: sway
    - role: veracrypt
    - role: vscodium
