common_packages:
  - aptitude # apt terminal gui
  - arandr # Visual frontend for xrandr
  - brightnessctl # Command line brightness control
  - curl # Client URL
  - feh # Image viewer and desktop wallpaper
  - fzf # Terminal Fuzzy finder
  - gimp # like photoshop, but for nix
  - git # Version control
  - htop # System monitor
  - make # make utility automation
  - mc # Terminal file manager
  - ncdu # Disk usage analyzer
  - neofetch # Terminal system info
  - pavucontrol # Pulseaudio volume control
  - peco # Terminal fuzzy finder
  - powertop # Energy optimizer
  - ranger # Terminal directory manager (vimlike)
  - rclone # rsync for cloud storage
  - solaar # logitech device manager
  - scrcpy # mirror android screen
  - syncthing # Sync folders between computers
  - tldr # like man but just examples
  - tlp # Energy optimizer
  - tree # Directory tree
  - vlc # Media player
  - wget # Web get
