- name: Import tdrop repo
  ansible.builtin.git:
    repo: https://github.com/noctuid/tdrop.git
    dest: "{{ current_directory }}"
    version: master

- name: Installs needed apt packages
  become: true
  loop: "{{ packages }}"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present

- name: install tdrop
  make:
    chdir: "{{ current_directory }}"
    target: install
  become: true
