- name: Install i3blocks
  become: true
  ansible.builtin.apt:
    name: i3blocks
    state: present

- name: Create a i3blocks config directory if it does not exist
  ansible.builtin.file:
    path: "{{ config_directory }}"
    state: directory
    recurse: true

- name: Check if i3blocks config file exists
  ansible.builtin.stat:
    path: "{{ config_directory }}/config"
  register: has_i3blocks_config
  failed_when: false

- name: Backup i3blocks config file
  ansible.builtin.command: mv {{ config_directory }}/config {{ config_directory }}/config.bak
  when: has_i3blocks_config.stat.exists
  changed_when: false

- name: Symlink i3blocks config file
  ansible.builtin.file:
    src: "{{ role_path }}/files/config"
    dest: "{{ config_directory }}/config"
    state: link

- name: Import i3blocks-contrib repo
  ansible.builtin.git:
    repo: https://github.com/vivien/i3blocks-contrib
    dest: "{{ config_directory }}/i3blocks-contrib"
    version: master
