- name: Installs needed apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: Add python rtx plugin
  ansible.builtin.command: "rtx plugin install python https://github.com/asdf-community/asdf-python.git"
  register: result
  failed_when: result.rc != 0 and not (result.stderr is search("Plugin named python already added"))
  changed_when: false

- name: Install latest python version
  ansible.builtin.command: "rtx install python@{{ python_version }}"
  changed_when: false

- name: Set python version
  ansible.builtin.command: "rtx global python@{{ python_version }}"
  changed_when: false
