- name: Installs needed apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: Install python version
  ansible.builtin.command: "mise use -g python@{{ python_version }}"
  changed_when: false
