- name: Installs conky system monitor for X
  become: true
  ansible.builtin.apt:
    name: conky
    state: present

- name: Check if .conkyrc exists
  ansible.builtin.stat:
    path: "{{ user_home }}/.conkyrc"
  register: conky_stat
  failed_when: false

- name: Backup .conkyrc
  ansible.builtin.command: mv {{ user_home }}/.conkyrc {{ user_home }}/.conkyrc.bak
  when: conky_stat.stat.exists

- name: Symlink .conkyrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/.conkyrc"
    dest: "{{ user_home }}/.conkyrc"
    state: link

- name: Make sure .config/autostart exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config/autostart"
    state: directory
    mode: u=rwx,g=r,o=r

- name: Symlink conky.desktop
  ansible.builtin.file:
    src: "{{ role_path }}/files/conky.desktop"
    dest: "{{ user_home }}/.config/autostart/conky.desktop"
    state: link
