- name: Install mise
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail # ansible-lint(risky-shell-pipe)
      curl https://mise.jdx.dev/install.sh | sh
  changed_when: false

- name: Install node
  ansible.builtin.import_role:
    name: node
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ user_home }}/.local/bin"

- name: Install python
  ansible.builtin.import_role:
    name: python
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ user_home }}/.local/bin"

- name: Install rust
  ansible.builtin.import_role:
    name: rust
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ user_home }}/.local/bin"

- name: Install golang
  ansible.builtin.import_role:
    name: golang
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ user_home }}/.local/bin"
