- name: Install i3
  become: true
  ansible.builtin.apt:
    name: i3
    state: present

- name: Install xss-lock to lock on lid close
  become: true
  ansible.builtin.apt:
    name: xss-lock
    state: present

- name: Create a i3 config directory if it does not exist
  ansible.builtin.file:
    path: "{{ user_home }}/.config/i3"
    state: directory
    recurse: true

- name: Check if i3 config file exists
  ansible.builtin.stat:
    path: "{{ user_home }}/.config/i3/config"
  register: has_i3_config
  failed_when: false

- name: Backup i3 config file
  ansible.builtin.command: mv {{ user_home }}/.config/i3/config {{ user_home }}/.config/i3/config.bak
  when: has_i3_config.stat.exists
  changed_when: false

- name: Symlink i3 config file
  ansible.builtin.file:
    src: "{{ role_path }}/files/config"
    dest: "{{ user_home }}/.config/i3/config"
    state: link

- name: Ensure .config/systemd/user exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config/systemd/user"
    state: directory
    recurse: true

- name: Symlink i3-session.target
  ansible.builtin.file:
    src: "{{ role_path }}/files/i3-session.target"
    dest: "{{ user_home }}/.config/systemd/user/i3-session.target"
    state: link

- name: Include touchpad config
  ansible.builtin.import_tasks: touchpad.yml
