- name: Installs needed apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: Install node version
  ansible.builtin.command: "mise use -g node@{{ node_version }}"
  changed_when: false
