- name: Run the equivalent of "apt-get update" as a separate step
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade existing packages
  become: true
  ansible.builtin.apt:
    upgrade: safe

- name: Installs common packages apt
  become: true
  loop: "{{ common_packages }}"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present

- name: Cleans packages | apt
  become: true
  ansible.builtin.apt:
    autoremove: true
