- name: Run the equivalent of "apt-get update" as a separate step
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade existing packages
  become: true
  ansible.builtin.apt:
    upgrade: safe

- name: Installs common packages apt
  become: true
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present

- name: Cleans packages | apt
  become: true
  ansible.builtin.apt:
    autoremove: true

- name: Set the default LANG
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/default/locale
    regexp: "^LANG="
    line: "LANG=C.UTF-8"
    state: present

- name: Set the default LANGUAGE
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/default/locale
    regexp: "^LANGUAGE="
    line: "LANGUAGE=C.UTF-8"
    state: present

- name: Set the default LC_ALL
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/default/locale
    regexp: "^LC_ALL="
    line: "LC_ALL=C.UTF-8"
    state: present

- name: Include nix
  ansible.builtin.import_tasks: nix.yml
