
- name: Installs neovim
  become: yes
  apt:
    name: neovim
    state: present

- name: Install pynvim
  command: python -m pip install pynvim

- name: Install spacevim
  shell: curl -sLf https://spacevim.org/install.sh | bash
  args:
    warn: no

- name: Make sure .SpaceVim.d exists
  file:
    path: "{{ user_home }}/.SpaceVim.d"
    state: directory

- name: Check if init.toml exists
  stat: path="{{user_home}}/.SpaceVim.d/init.toml"
  register: spacevim_init_stat
  failed_when: False

- name: Backup init.toml
  command: mv {{user_home}}/.SpaceVim.d/init.toml {{user_home}}/.SpaceVim.d/init.toml.bak
  when: spacevim_init_stat.stat.exists

- name: Symlink init.toml
  file:
    src: "{{ role_path }}/files/init.toml"
    dest: "{{ user_home }}/.SpaceVim.d/init.toml"
    state: link