- name: Install neovim
  ansible.builtin.command: nix-env -iA nixpkgs.neovim
  environment:
    PATH: "{{ ansible_env.PATH }}:/nix/var/nix/profiles/default/bin"
  changed_when: false

- name: Check if .vimrc exists
  ansible.builtin.stat:
    path: "{{ user_home }}/.vimrc"
  register: vimrc_stat
  failed_when: false

- name: Backup .vimrc
  ansible.builtin.command: mv {{ user_home }}/.vimrc {{ user_home }}/.vimrc.bak
  when: vimrc_stat.stat.exists
  changed_when: false

- name: Symlink .vimrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/.vimrc"
    dest: "{{ user_home }}/.vimrc"
    state: link

- name: Check if nvim exists
  ansible.builtin.stat:
    path: "{{ user_home }}/.config/nvim"
  register: nvim_stat
  failed_when: false

- name: Backup nvim
  ansible.builtin.command: mv {{ user_home }}/.config/nvim {{ user_home }}/.config/nvim.bak
  when: nvim_stat.stat.exists
  changed_when: false

- name: Symlink nvim
  ansible.builtin.file:
    src: "{{ role_path }}/files/nvim"
    dest: "{{ user_home }}/.config/nvim"
    state: link

- name: Tree-sitter CLI Install
  ansible.builtin.command: "{{ rust_path }}/cargo install tree-sitter-cli"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ rust_path }}"
    CARGO_HOME: "{{ cargo_home }}"
    RUSTUP_HOME: "{{ rustup_home }}"
  changed_when: false
