- name: Install rofi-calc dependencies
  become: true
  loop: "{{ packages }}"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present

- name: Import rofi-calc repo
  ansible.builtin.git:
    repo: https://github.com/svenstaro/rofi-calc
    dest: "{{ current_directory }}"
    version: master

- name: Update configuration files
  ansible.builtin.command:
    cmd: autoreconf -i
    chdir: "{{ current_directory }}"
  changed_when: false

- name: Clear configuration
  ansible.builtin.file:
    path: "{{ current_directory }}/build"
    state: absent

- name: Creates build directory if not exists
  ansible.builtin.file:
    path: "{{ current_directory }}/build"
    state: directory
    mode: u=rwx,g=r,o=r

- name: Configure
  ansible.builtin.command:
    cmd: ../configure
    chdir: "{{ current_directory }}/build"
  changed_when: false

- name: Make
  ansible.builtin.command:
    cmd: make
    chdir: "{{ current_directory }}/build"
  changed_when: false

- name: Install
  become: true
  ansible.builtin.command:
    cmd: make install
    chdir: "{{ current_directory }}/build"
  changed_when: false
