- name: Copy fonts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ font_directory }}/"
    mode: u=rwx
  with_fileglob:
    - "{{ role_path }}/files/*"

- name: Regenerate font cache
  ansible.builtin.command: fc-cache -f -v
  changed_when: false
